POST https://laravel-rpb57418.snowflakecomputing.com/api/v2/statements
Authorization: Bearer {{SNOWFLAKE_BEARER_TOKEN}}
Content-Type: application/json
Accept: application/json
{
    "role": "ANALYZER_ROLE",
    "statement": "select * from production.reverse_etl.company_traits limit 30"
}
